# yazi.toml
[manager]
show_hidden = true

[opener]
play = [
    { run = 'vlc "$@"', orphan = true, for = "unix" },
]
edit = [
    { run = '${EDITOR:-nvim} "$@"', block = true, for = "unix" }
]
open = [
    { run = 'xdg-open "$@"', desc = "Open" },
]

[open]
prepend_rules = [
    # Explicit rule for mp4 first
    { name = "*.mp4", use = "play" },
    # Other media file types
    { name = "*.mp3", use = "play" },
    { name = "*.avi", use = "play" },
    { name = "*.mkv", use = "play" },
    { name = "*.webm", use = "play" },
    { name = "*.ogg", use = "play" },
    { name = "*.flac", use = "play" },
    # Edit-related file types
    { name = "*.json", use = "edit" },
    { name = "*.sh", use = "edit" },
    { name = "*.toml", use = "edit" },
    { name = "*.y*ml", use = "edit" },
    { name = "*config", use = "edit" },
    { name = "*.cfg", use = "edit" },
    { name = "*env", use = "edit" },
    { name = "*.d", use = "edit" },
    { name = "*.md", use = "edit" },
    { name = "*.txt", use = "edit" },
    { name = ".zsh*", use = "edit" },
    { name = "*.ini", use = "edit" },
    { name = "*.lua", use = "edit" },
    { name = "*.xml", use = "edit" },
    { name = "*.log", use = "edit" },
    # Open with normal / gnome / kde
    { name = "*.ods", use = "open" },
    { name = "*.pdf", use = "open" },
]
append_rules = [
    { name = "*", use = "edit" },
]
